[workspace]
members = [
	"bachd",
	"modules/dummy",
	"modules/stdlogger",
	"modules/rsync",
	"modules/noreply-select",
	"modules/reporter",
	"bach-module",
	"bach-module-tests",
	"bach-bus",
]

exclude = [
	"bacsh"
]

